import { textFont } from '@/utils/fonts'
import './globals.css'
import 'flatpickr/dist/themes/material_green.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={`${textFont.className} `}>
      <body>{children}</body>
    </html>
  )
}
