import { textFont } from '@/utils/fonts'
import './globals.css'
import 'flatpickr/dist/themes/material_green.css'
import ToasterComponent from '@/lib/Toaster'
import NextAuthProvider from '@/components/providers/NextAuthProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={`${textFont.className} h-full `}>
      <body>
        <NextAuthProvider>
          {children}
          <ToasterComponent />
        </NextAuthProvider>
      </body>
    </html>
  )
}
